import type { IncomeSource, Expense, Category } from './types';

export const testCategories: Category[] = [
  { id: 'cat-housing', name: 'Housing', color: '#d98f8f', sortOrder: 0 },
  { id: 'cat-transport', name: 'Transport', color: '#7d9fd4', sortOrder: 1 },
  { id: 'cat-utilities', name: 'Utilities', color: '#e0a877', sortOrder: 2 },
  { id: 'cat-insurance', name: 'Insurance', color: '#a394d6', sortOrder: 3 },
  { id: 'cat-subscriptions', name: 'Subscriptions', color: '#d691b0', sortOrder: 4 },
  { id: 'cat-savings', name: 'Savings/Investment', color: '#6fb3ac', sortOrder: 5 },
  { id: 'cat-loans', name: 'Loans', color: '#cf8a8a', sortOrder: 6 },
  { id: 'cat-phone', name: 'Phone', color: '#8b80cc', sortOrder: 7 },
  { id: 'cat-storage', name: 'Storage', color: '#b596d6', sortOrder: 8 },
];

// From Sheet3 of the spreadsheet
export const testIncome: IncomeSource[] = [
  {
    id: 'inc-paycheck',
    name: 'Paycheck',
    amount: 1268,
    isVariable: false,
    schedule: {
      interval: 2, unit: 'week',
      dayOfMonth: null,
      dayOfWeek: 5, // Friday
      startDate: '2023-11-01',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'day_before',
    },
  },
];

export const testExpenses: Expense[] = [
  {
    id: 'exp-rent',
    name: 'Rent',
    amount: 792.5,
    categoryId: 'cat-housing',
    type: 'recurring',
    isVariable: false,
    tier: 0,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 1,
      dayOfWeek: null,
      startDate: '2023-11-01',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-electric',
    name: 'Electric',
    amount: 42.5,
    categoryId: 'cat-utilities',
    type: 'recurring',
    isVariable: true,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 7,
      dayOfWeek: null,
      startDate: '2023-11-07',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-gas-utility',
    name: 'Gas (Utility)',
    amount: 12.5,
    categoryId: 'cat-utilities',
    type: 'recurring',
    isVariable: true,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 23,
      dayOfWeek: null,
      startDate: '2023-10-23',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-internet',
    name: 'Internet',
    amount: 27.5,
    categoryId: 'cat-utilities',
    type: 'recurring',
    isVariable: false,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 19,
      dayOfWeek: null,
      startDate: '2023-10-19',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-uv-insurance',
    name: 'UV Insurance',
    amount: 184.44,
    categoryId: 'cat-insurance',
    type: 'recurring',
    isVariable: false,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 3, unit: 'month', // every 6 months ~= 2 quarters (we'll use semiannual via quarterly x2 approach)
      dayOfMonth: 5,
      dayOfWeek: null,
      startDate: '2023-10-05',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-uv-inspection',
    name: 'UV Inspection',
    amount: 85,
    categoryId: 'cat-transport',
    type: 'recurring',
    isVariable: false,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year',
      dayOfMonth: 1,
      dayOfWeek: null,
      startDate: '2023-09-01',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-uv-maintenance',
    name: 'UV Maintenance',
    amount: 50,
    categoryId: 'cat-transport',
    type: 'recurring',
    isVariable: true,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 3, unit: 'month', // every 6 months
      dayOfMonth: 30,
      dayOfWeek: null,
      startDate: '2023-10-30',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-ktm-insurance',
    name: 'KTM Insurance',
    amount: 71.86,
    categoryId: 'cat-insurance',
    type: 'recurring',
    isVariable: false,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year',
      dayOfMonth: 7,
      dayOfWeek: null,
      startDate: '2023-10-07',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-ktm-inspection',
    name: 'KTM Inspection',
    amount: 23,
    categoryId: 'cat-transport',
    type: 'recurring',
    isVariable: false,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year', // every 24 months, but annual is closest we have
      dayOfMonth: 30,
      dayOfWeek: null,
      startDate: '2023-10-30',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-ktm-maintenance',
    name: 'KTM Maintenance',
    amount: 150,
    categoryId: 'cat-transport',
    type: 'recurring',
    isVariable: true,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year',
      dayOfMonth: 30,
      dayOfWeek: null,
      startDate: '2023-10-30',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-phone',
    name: 'Phone Plan',
    amount: 360,
    categoryId: 'cat-phone',
    type: 'recurring',
    isVariable: false,
    tier: 1,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year',
      dayOfMonth: 2,
      dayOfWeek: null,
      startDate: '2023-11-02',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-investment',
    name: 'Investment Edward',
    amount: 100,
    categoryId: 'cat-savings',
    type: 'recurring',
    isVariable: false,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 4,
      dayOfWeek: null,
      startDate: '2023-11-04',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-audible',
    name: 'Audible Sub',
    amount: 120,
    categoryId: 'cat-subscriptions',
    type: 'subscription',
    isVariable: false,
    tier: 3,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'year',
      dayOfMonth: 1,
      dayOfWeek: null,
      startDate: '2023-05-01',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-storage',
    name: 'Storage',
    amount: 120,
    categoryId: 'cat-storage',
    type: 'recurring',
    isVariable: false,
    tier: 2,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 1,
      dayOfWeek: null,
      startDate: '2023-11-01',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
  {
    id: 'exp-loan',
    name: 'Loan',
    amount: 396.88,
    categoryId: 'cat-loans',
    type: 'recurring',
    isVariable: false,
    tier: 0,
    isAutoCut: false,
    schedule: {
      interval: 1, unit: 'month',
      dayOfMonth: 4,
      dayOfWeek: null,
      startDate: '2023-11-04',
      endDate: null,
      weekendRule: 'as_is',
      holidayRule: 'as_is',
    },
  },
];

export const TEST_BALANCE = 1500;
export const TEST_BUFFER = 0;
